CREATE TABLE users(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20),
  age INT
);

CREATE TABLE auto (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  model VARCHAR(20),
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

-- ALTER TABLE auto ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;